version: '{build}'
platform: x64
configuration: Release
os: Visual Studio 2015

clone_depth: 50
clone_folder: c:\gopath\src\github.com\cretz\tor-static

environment:
  GOPATH: c:\gopath

install:
  - set PATH=C:\msys64\usr\bin;%PATH%
  - set MSYSTEM=MINGW64
  - bash -lc "pacman -Sy --needed base-devel mingw-w64-i686-toolchain mingw-w64-x86_64-toolchain git mingw-w64-i686-cmake mingw-w64-x86_64-cmake"

before_build:
  - set MSYSTEM=MINGW64
  - cd c:\gopath\src\github.com\cretz\tor-static
  - git submodule update --init --recursive

build_script:
  - set MSYSTEM=MINGW64
  - bash -lc "export PATH=/mingw64/bin:$PATH && cd /c/gopath/src/github.com/cretz/tor-static && /c/go/bin/go run build.go -verbose build-all"

test_script:
  - go get -u github.com/cretz/bine
  - cd c:\gopath\src\github.com\cretz\tor-static
  - go test -v build_test.go -tor.verbose

after_build:
  - go run build.go package-libs