language: go
go: 1.11.x
sudo: false

matrix:
  include:
    - name: linux-amd64
      os: linux
      dist: xenial
      env: CGO_ENABLED=1 GOOS=linux GOARCH=amd64 BINARY=linux-amd64
      install:
        - sudo apt-get install build-essential
        - sudo apt-get install libtool
        - sudo apt-get install autopoint
    - name: darwin-amd64
      os: osx
      env: CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 BINARY=darwin-amd64
      install:
        - brew install libtool
        - brew install gettext
    - name: windows-amd64
      os: windows
      env: CGO_ENABLED=1 GOOS=windows GOARCH=amd64 BINARY=windows-amd64.exe
      install:
        - choco install msys2
        - refreshenv
        - msys2
        - pacman -Syuu
        - pacman -Sy --needed base-devel mingw-w64-i686-toolchain mingw-w64-x86_64-toolchain \
          git subversion mercurial \
          mingw-w64-i686-cmake mingw-w64-x86_64-cmake

script:
  - go run build.go build-all
  - go run build.go show-libs

deploy:
  if: branch = master
  provider: releases
  api_key: "${GITHUB_PAT}"
  file: "tor-static-${BINARY}"
  skip_cleanup: true
  draft: true
  on:
    tags: true