language: go
go: 1.11.x
sudo: false

matrix:
  include:
    - name: linux-amd64
      os: linux
      dist: xenial
      env: CGO_ENABLED=1 GOOS=linux GOARCH=amd64 BINARY=linux-amd64
      install:
        - sudo apt-get install build-essential
        - sudo apt-get install libtool
        - sudo apt-get install autopoint
    - name: darwin-amd64
      os: osx
      env: CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 BINARY=darwin-amd64
      install:
        - brew install libtool
        - brew install gettext
    - name: windows-amd64
      os: windows
      env: CGO_ENABLED=1 GOOS=windows GOARCH=amd64 BINARY=windows-amd64.exe
      install:
        - choco install -y msys2
        - cd c:\tools\msys64
        - msys2_shell.bat \
          pacman -Syuu \
          exit
        - msys2_shell.bat \
          # possibly use pacman -Syu below
          pacman -Sy --needed base-devel mingw-w64-i686-toolchain mingw-w64-x86_64-toolchain \
          git subversion mercurial \
          mingw-w64-i686-cmake mingw-w64-x86_64-cmake

script:
  - go run build.go build-all
  - go run build.go show-libs

after_success:
  - mkdir deploy
  - mv Ltor/src/core/ltor-app ./deploy/Ltor/src/core/ltor-app
  - mv Ltor/src/lib/ltor-compress ./deploy/Ltor/src/lib/ltor-compress
  - mv Ltor/src/lib/ltor-evloop ./deploy/Ltor/src/lib/ltor-evloop
  - mv Ltor/src/lib/ltor-tls ./deploy/Ltor/src/lib/ltor-tls
  - mv Ltor/src/lib/ltor-crypt-ops ./deploy/Ltor/src/lib/ltor-crypt-ops
  - mv Ltor/src/lib/lcurve25519_donna ./deploy/Ltor/src/lib/lcurve25519_donna
  - mv Ltor/src/lib/ltor-geoip ./deploy/Ltor/src/lib/ltor-geoip
  - mv Ltor/src/lib/ltor-process ./deploy/Ltor/src/lib/ltor-process
  - mv Ltor/src/lib/ltor-time ./deploy/Ltor/src/lib/ltor-time
  - mv Ltor/src/lib/ltor-fs ./deploy/Ltor/src/lib/ltor-fs
  - mv Ltor/src/lib/ltor-encoding ./deploy/Ltor/src/lib/ltor-encoding
  - mv Ltor/src/lib/ltor-sandbox ./deploy/Ltor/src/lib/ltor-sandbox
  - mv Ltor/src/lib/ltor-container ./deploy/Ltor/src/lib/ltor-container
  - mv Ltor/src/lib/ltor-net ./deploy/Ltor/src/lib/ltor-net
  - mv Ltor/src/lib/ltor-thread ./deploy/Ltor/src/lib/ltor-thread
  - mv Ltor/src/lib/ltor-memarea ./deploy/Ltor/src/lib/ltor-memarea
  - mv Ltor/src/lib/ltor-math ./deploy/Ltor/src/lib/ltor-math
  - mv Ltor/src/lib/ltor-meminfo ./deploy/Ltor/src/lib/ltor-meminfo
  - mv Ltor/src/lib/ltor-osinfo ./deploy/Ltor/src/lib/ltor-osinfo
  - mv Ltor/src/lib/ltor-log ./deploy/Ltor/src/lib/ltor-log
  - mv Ltor/src/lib/ltor-lock ./deploy/Ltor/src/lib/ltor-lock
  - mv Ltor/src/lib/ltor-fdio ./deploy/Ltor/src/lib/ltor-fdio
  - mv Ltor/src/lib/ltor-string ./deploy/Ltor/src/lib/ltor-string
  - mv Ltor/src/lib/ltor-term ./deploy/Ltor/src/lib/ltor-term
  - mv Ltor/src/lib/ltor-smartlist-core ./deploy/Ltor/src/lib/ltor-smartlist-core
  - mv Ltor/src/lib/ltor-malloc ./deploy/Ltor/src/lib/ltor-malloc
  - mv Ltor/src/lib/ltor-wallclock ./deploy/Ltor/src/lib/ltor-wallclock
  - mv Ltor/src/lib/ltor-err ./deploy/Ltor/src/lib/ltor-err
  - mv Ltor/src/lib/ltor-intmath ./deploy/Ltor/src/lib/ltor-intmath
  - mv Ltor/src/lib/ltor-ctime ./deploy/Ltor/src/lib/ltor-ctime
  - mv Ltor/src/lib/ltor-trace ./deploy/Ltor/src/lib/ltor-trace
  - mv Ltor/src/ext/keccak-tiny/lkeccak-tiny ./deploy/Ltor/src/ext/keccak-tiny/lkeccak-tiny
  - mv Ltor/src/ext/ed25519/ref10/led25519_ref10 ./deploy/Ltor/src/ext/ed25519/ref10/led25519_ref10
  - mv Ltor/src/ext/ed25519/donna/led25519_donna ./deploy/Ltor/src/ext/ed25519/donna/led25519_donna
  - mv Ltor/src/trunnel/lor-trunnel ./deploy/Ltor/src/trunnel/lor-trunnel
  - mv Llibevent/dist/lib/levent ./deploy/Llibevent/dist/lib/levent
  - mv Lxz/dist/lib/llzma ./deploy/Lxz/dist/lib/llzma
  - mv Lzlib/dist/lib/lz ./deploy/Lzlib/dist/lib/lz
  - mv Lopenssl/dist/lib/lssl ./deploy/Lopenssl/dist/lib/lssl
  - mv Lopenssl/dist/lib/lcrypto ./deploy/Lopenssl/dist/lib/lcrypto
  - zip -r tor-static-${BINARY}.zip deploy

deploy:
  if: branch = integrate-ci
  provider: releases
  api_key: "${GITHUB_PAT}"
  file: "tor-static-${BINARY}.zip"
  skip_cleanup: true
  draft: true
  on:
    tags: true