FROM ubuntu:rolling
RUN apt-get update
RUN apt install locales -y
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
RUN locale-gen
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get upgrade -y
RUN apt-get install -y git build-essential libtool autopoint wget upx-ucl
ADD . /build/
WORKDIR /build
RUN wget https://golang.org/dl/go1.14.6.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.14.6.linux-amd64.tar.gz                                                                                                                                       
RUN rm go1.14.6.linux-amd64.tar.gz                                                                                                                                                           
RUN git clone https://github.com/cretz/tor-static.git --recursive --depth=1                                                                                                                  
WORKDIR /build/tor-static
