name: Build static binaries

on: push
# on:
#   release:
#     types: [created]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      # Download dependencies depending on platform
      - name: Download build tools [linux]
        if: runner.os == 'Linux'
        run: sudo apt-get install build-essential libtool autopoint
      - name: Download build tools [mac]
        if: runner.os == 'macOS'
        run: brew install libtool automake gettext
      - name: Setup MinGW [windows]
        if: runner.os == 'Windows'
        uses: egor-tensin/setup-mingw@v2

      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download dependencies
        run: git submodule update --init --recursive
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.17.0'
      - name: Build dependencies
        run: go run build.go -verbose build-all
      - name: Upload tor binary
        uses: actions/upload-artifact@v3
        with:
          name: tor-${{ matrix.os }}
          path:
            tor/src/app/tor

  test:
    name: Run tests on ${{ matrix.os }}
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download dependencies
        run: git submodule update --init --recursive
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.17.0'
      - name: Run tests
        run: go test .
